USE [master]
GO
/****** Object:  Database [PruebaBAM]    Script Date: 14/09/2021 08:42:18 p. m. ******/
CREATE DATABASE [PruebaBAM]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PruebaBAM', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\PruebaBAM.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PruebaBAM_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\PruebaBAM_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [PruebaBAM] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PruebaBAM].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PruebaBAM] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PruebaBAM] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PruebaBAM] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PruebaBAM] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PruebaBAM] SET ARITHABORT OFF 
GO
ALTER DATABASE [PruebaBAM] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PruebaBAM] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PruebaBAM] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PruebaBAM] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PruebaBAM] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PruebaBAM] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PruebaBAM] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PruebaBAM] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PruebaBAM] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PruebaBAM] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PruebaBAM] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PruebaBAM] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PruebaBAM] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PruebaBAM] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PruebaBAM] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PruebaBAM] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PruebaBAM] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PruebaBAM] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PruebaBAM] SET  MULTI_USER 
GO
ALTER DATABASE [PruebaBAM] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PruebaBAM] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PruebaBAM] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PruebaBAM] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PruebaBAM] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PruebaBAM] SET QUERY_STORE = OFF
GO
USE [PruebaBAM]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [PruebaBAM]
GO
/****** Object:  Table [dbo].[Producto]    Script Date: 14/09/2021 08:42:18 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Producto](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](100) NOT NULL,
	[precio] [float] NOT NULL,
	[descripcion] [varchar](300) NULL,
 CONSTRAINT [PK_Producto] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Producto_nombre]    Script Date: 14/09/2021 08:42:18 p. m. ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Producto_nombre] ON [dbo].[Producto]
(
	[nombre] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  StoredProcedure [dbo].[Productos_sp]    Script Date: 14/09/2021 08:42:18 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[Productos_sp]
	@query			varchar(100),
	@id				int = null,
	@nombre			varchar(100) = null,
	@precio			float = null,
	@descripcion	varchar(300) = null
AS
BEGIN

	if @query = 'insertar'

		insert into Producto(nombre, precio, descripcion)
		values(@nombre, @precio, @descripcion)

	else if @query = 'modificar'

		update Producto
		set nombre = @nombre, precio = @precio, descripcion = @descripcion
		where id = @id

	else if @query = 'eliminar'

		delete from Producto
		where id = @id

	else if @query = 'consultar'

		select *
		from Producto
		order by nombre

END
GO
USE [master]
GO
ALTER DATABASE [PruebaBAM] SET  READ_WRITE 
GO
